/* 此规范为 uni 规范，可以按照自己的需要选择是否实现 */
import { PreferencesErrorCode, PreferencesFail } from "./interface.uts"
/**
 * 错误主题
 * 注意：错误主题一般为插件名称，每个组件不同，需要使用时请更改。
 * [可选实现]
 */
export const UniErrorSubject = 'jiannor-preference';


/**
 * 错误信息
 * @UniError
 * [可选实现]
 */
export const PreferencesAPIErrors : Map<PreferencesErrorCode, string> = new Map([
  /**
   * 错误码及对应的错误信息
   */
  [9010001, '获取Preferences失败'],
  [9010002, '设置Preferences失败'],
  [9010003, '删除Preferences失败'],
  [9010004, '清空Preferences失败'],
  [9010005, '参数错误'],
  [9010006, '删除Preferences键值失败'],
]);


/**
 * 错误对象实现
 */
export class PreferencesFailImpl extends UniError implements PreferencesFail {
  
  override errCode: PreferencesErrorCode

  /**
   * 错误对象构造函数
   */
  constructor(errCode : PreferencesErrorCode) {
    super();
    this.errSubject = UniErrorSubject;
    this.errCode = errCode;
    this.errMsg = PreferencesAPIErrors.get(errCode) ?? "";
  }
}
